# Generated by Django 5.2.1 on 2025-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_bankaccount_options_alter_card_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcardbill',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('overdue', 'Overdue')], default='unpaid', max_length=20),
        ),
    ]
